version: '3.1'

services:

  data:
    image: postgres
    restart: always
    container_name: postgres-server
    hostname: postgres-server
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "********"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data


  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@site.com"
      PGADMIN_DEFAULT_PASSWORD: "*********"
    ports:
      - 5050:80
volumes:
   data:
